baseURL = "https://noahpaladino.com/"
locale = "en-us"
title = "Noah Paladino"

enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  shortTitle = "Noah Paladino"
  email = "noah@noahpaladino.com"
  description = "Noah Paladino, PhD Candidate in Physics at MIT, researching dark sector detector instrumentation and data acquisition for particle physics experiments."

[services.googleAnalytics]
  id = "G-BWXVTW93YK"

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]

[outputFormats.RSS]
  baseName = "feed"

[markup.goldmark.extensions.passthrough]
  enable = true

  [markup.goldmark.extensions.passthrough.delimiters]
    block = [["\\[", "\\]"]]
    inline = [["\\(", "\\)"]]
